swagger: '2.0'
info:
  version: '1.0'
  title: ShipmentRequests
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /shipment-requests:
    get:
      description: Get Shippment Request list
      summary: Get All User ShipmentRequests
      tags:
      - Misc
      operationId: ShipmentRequestsGet
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /shipment-requests
          headers:
            Authorization: '{{auth_token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get All User ShipmentRequests
        x-testDescription: Get Shippment Request list
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      description: ''
      summary: Add New ShipmentRequests
      tags:
      - Misc
      operationId: ShipmentRequestsPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AddNewShipmentrequestsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      description: ''
      summary: Edit SR Collection
      tags:
      - Misc
      operationId: ShipmentRequestsPatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditSrCollectionrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /shipment-requests
          headers:
            Content-Type: application/json
            Authorization: '{{auth_token}}'
          body: >-
            {
              "ids": [
                1,
                2
              ],
              "data": {
              	 "ready_to_send": {
            		"begin": "2017-08-30T10:55:42+0100",
            		"end" : "2017-08-30T10:55:42+0100"
            	  },
              	  "spots": [
            	   {
                  "name": "Lidl",
                  "type": "unloading",
                  "timespans": {
                    "begin": "2018-07-20T10:47:42+0100",
                    "end": "2018-07-20T10:47:42+0100"
                  },
                  "place": {
                    "address": {
                      "locality": "Monachium",
                      "postal_code": "53-342",
                      "country": "DE",
                      "street": "Zwidnicka",
                      "number": "1"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                },
                   {
                  "name": "Lidl",
                  "type": "loading",
                  "timespans": {
                    "begin": "2018-07-20T10:47:42+0100",
                    "end": "2018-07-20T10:47:42+0100"
                  },
                  "place": {
                    "address": {
                      "locality": "Monachium",
                      "postal_code": "53-342",
                      "country": "DE",
                      "street": "Zwidnicka",
                      "number": "1"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                }
              ]
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Edit SR Collection
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /shipment-requests/3345:
    put:
      description: ''
      summary: Edit ShipmentReqests (multi)
      tags:
      - Misc
      operationId: ShipmentRequests3345Put
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditShipmentreqests(multi)request'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /shipment-requests/3345
          headers:
            Content-Type: application/json
            Authorization: '{{auth_token}}'
          body: >-
            {
              "name": "13.07.2017 2005",
              "number": "123456789",
              "status": "in_progress",
              "ready_to_send": "2018-04-11T10:47:42+0100",
              "freights": [],
              "spots": [
                {
                  "name": "Hurtownia",
                  "type": "loading",
                  "timespans": {
                    "begin": "2018-04-15T10:47:42+0100",
                    "end": "2018-04-15T10:47:42+0100"
                  },
                  "place": {
                    "address": {
                      "locality": "Munchen",
                      "postal_code": "80331",
                      "country": "DE",
                      "street": "Ulica",
                      "number": "2"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                },
                {
                  "name": "Lidl",
                  "type": "unloading",
                  "timespans": {
                    "begin": "2018-04-15T10:47:42+0100",
                    "end": "2018-04-15T10:47:42+0100"
                  },
                  "place": {
                    "address": {
                      "locality": "WrocBaw",
                      "postal_code": "50-064",
                      "country": "PL",
                      "street": "Zwidnicka",
                      "number": "1"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                }
              ],
              "loads": [
                {
                  "name": "Chemicals",
                  "description": "Test",
                  "type_of_load": "box",
                  "weight": {
                    "value": 50,
                    "unit_code": "kg"
                  },
                  "height": {
                    "value": 26,
                    "unit_code": "kg"
                  },
                  "width": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "length": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "volume": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "amount": 50000,
                  "requirements": {
                    "required_adr_classes": [
                      "1"
                    ],
                    "required_ways_of_loading": [
                      "side"
                    ],
                    "required_truck_bodies": [
                      "20"
                    ],
                    "is_truck_crane_required": true,
                    "is_lift_required": false,
                    "is_for_clearance": true,
                    "is_tir_cable_required": true,
                    "is_ftl": true,
                    "is_tracking_system_required": true,
                    "shipping_remarks": "brak dodatkowych wymagaD"
                  }
                }
              ]
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Edit ShipmentReqests (multi)
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /api/rest/v1/shipment-requests:
    patch:
      description: ''
      summary: Edit SR Collection(local)
      tags:
      - Misc
      operationId: ApiRestV1ShipmentRequestsPatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditSrCollection(local)request'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /api/rest/v1/shipment-requests
          headers:
            Content-Type: application/json
            Authorization: '{{auth_token}}'
          body: "{\n	\"ids\":[\n		1,\n		2\n	],\n	\"data\": {\n		\"spots\": [\n			{\n				\"name\":\"Logintrans Sp. z o. o.2\",\n				\"type\":\"loading\",\n				\"place\": {\n					\"address\": {\n						\"locality\": \"WrocBaw\",\n						\"postal_code\": \"52-200\",\n						\"country\": \"PL\",\n						\"street\": \"Chabrowa\",\n						\"number\": \"4\"\n						\n					},\n					\"coordinates\": {\n						\"latitude\": -90, \n						\"longitude\": -180\n					}\n				}\n			}\n		]\n	}\n}\n"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Edit SR Collection(local)
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /shipment-requests/69:
    patch:
      description: ''
      summary: Patch ShipmentReqests
      tags:
      - Misc
      operationId: ShipmentRequests69Patch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PatchShipmentreqestsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /shipment-requests/69
          headers:
            Content-Type: application/json
            Authorization: '{{auth_token}}'
          body: >-
            {
              "name": "13.07.2017 2005",
              "number": "123456789",
              "status": "in_progress",
              "ready_to_send": {
                "begin": "2017-10-19T00:00:00+0200",
                "end" : "2017-10-19T00:00:00+0200"
              },
              "freights": [],
              "spots": [
                {
                  "name": "Hurtownia",
                  "type": "loading",
                  "timespans": {
                    "begin": "2017-10-19T00:00:00+0200",
                    "end": "2017-10-19T00:00:00+0200"
                  },
                  "place": {
                    "address": {
                      "locality": "Munchen",
                      "postal_code": "80331",
                      "country": "DE",
                      "street": "Ulica",
                      "number": "2"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                },
                {
                  "name": "Lidl",
                  "type": "unloading",
                  "timespans": {
                    "begin": "2017-10-19T00:00:00+0200",
                    "end": "2017-10-19T00:00:00+0200"
                  },
                  "place": {
                    "address": {
                      "locality": "WrocBaw",
                      "postal_code": "50-064",
                      "country": "PL",
                      "street": "Zwidnicka",
                      "number": "1"
                    },
                    "coordinates": {
                      "latitude": -90.0,
                      "longitude": -180.0
                    }
                  }
                }
              ],
              "loads": [
                {
                  "name": "Chemicals",
                  "description": "Test",
                  "type_of_load": "box",
                  "weight": {
                    "value": 50,
                    "unit_code": "kg"
                  },
                  "height": {
                    "value": 26,
                    "unit_code": "kg"
                  },
                  "width": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "length": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "volume": {
                    "value": 16,
                    "unit_code": "kg"
                  },
                  "amount": 50000,
                  "requirements": {
                    "required_adr_classes": [
                      "1"
                    ],
                    "required_ways_of_loading": [
                      "side"
                    ],
                    "required_truck_bodies": [
                      "20"
                    ],
                    "is_truck_crane_required": true,
                    "is_lift_required": false,
                    "is_for_clearance": true,
                    "is_tir_cable_required": true,
                    "is_ftl": true,
                    "is_tracking_system_required": true,
                    "shipping_remarks": "brak dodatkowych wymagaD"
                  }
                }
              ]
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Patch ShipmentReqests
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  AddNewShipmentrequestsrequest:
    title: Add New ShipmentRequestsRequest
    type: object
    properties:
      name:
        description: ''
        example: 14.09.2017 1048
        type: string
      number:
        description: ''
        example: 14.09.2017 1048
        type: string
      status:
        description: ''
        example: in_progress
        type: string
      ready_to_send:
        $ref: '#/definitions/ReadyToSend'
      freights:
        description: ''
        example: []
        type: array
        items:
          type: string
      spots:
        description: ''
        example:
        - name: ChemicalsCompany
          type: loading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Opole
              postal_code: 42-256
              country: PL
              street: Street
              number: 2
            coordinates:
              latitude: -90
              longitude: -180
        - name: Lidl
          type: unloading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Monachium
              postal_code: 53-342
              country: DE
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        type: array
        items:
          $ref: '#/definitions/Spot'
      loads:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Load'
    required:
    - name
    - number
    - status
    - ready_to_send
    - freights
    - spots
    - loads
  ReadyToSend:
    title: ReadyToSend
    example:
      begin: 2018-08-31T09:47:42.0000000+00:00
      end: 2018-08-31T09:47:42.0000000+00:00
    type: object
    properties:
      begin:
        description: ''
        example: 8/31/2018 9:47:42 AM
        type: string
      end:
        description: ''
        example: 8/31/2018 9:47:42 AM
        type: string
    required:
    - begin
    - end
  Spot:
    title: Spot
    example:
      name: ChemicalsCompany
      type: loading
      timespans:
        begin: 2018-07-20T09:47:42.0000000+00:00
        end: 2018-07-20T09:47:42.0000000+00:00
      place:
        address:
          locality: Opole
          postal_code: 42-256
          country: PL
          street: Street
          number: 2
        coordinates:
          latitude: -90
          longitude: -180
    type: object
    properties:
      name:
        description: ''
        example: ChemicalsCompany
        type: string
      type:
        description: ''
        example: loading
        type: string
      timespans:
        $ref: '#/definitions/Timespans'
      place:
        $ref: '#/definitions/Place'
    required:
    - name
    - type
    - timespans
    - place
  Timespans:
    title: Timespans
    example:
      begin: 2018-07-20T09:47:42.0000000+00:00
      end: 2018-07-20T09:47:42.0000000+00:00
    type: object
    properties:
      begin:
        description: ''
        example: 7/20/2018 9:47:42 AM
        type: string
      end:
        description: ''
        example: 7/20/2018 9:47:42 AM
        type: string
    required:
    - begin
    - end
  Place:
    title: Place
    example:
      address:
        locality: Opole
        postal_code: 42-256
        country: PL
        street: Street
        number: 2
      coordinates:
        latitude: -90
        longitude: -180
    type: object
    properties:
      address:
        $ref: '#/definitions/Address'
      coordinates:
        $ref: '#/definitions/Coordinates'
    required:
    - address
    - coordinates
  Address:
    title: Address
    example:
      locality: Opole
      postal_code: 42-256
      country: PL
      street: Street
      number: 2
    type: object
    properties:
      locality:
        description: ''
        example: Opole
        type: string
      postal_code:
        description: ''
        example: 42-256
        type: string
      country:
        description: ''
        example: PL
        type: string
      street:
        description: ''
        example: Street
        type: string
      number:
        description: ''
        example: 2
        type: string
    required:
    - locality
    - postal_code
    - country
    - street
    - number
  Coordinates:
    title: Coordinates
    example:
      latitude: -90
      longitude: -180
    type: object
    properties:
      latitude:
        description: ''
        example: -90
        type: number
        format: double
      longitude:
        description: ''
        example: -180
        type: number
        format: double
    required:
    - latitude
    - longitude
  Load:
    title: Load
    type: object
    properties:
      name:
        description: ''
        example: Warzywa
        type: string
      description:
        description: ''
        example: Test
        type: string
      type_of_load:
        description: ''
        example: box
        type: string
      weight:
        $ref: '#/definitions/Weight'
      height:
        $ref: '#/definitions/Height'
      width:
        $ref: '#/definitions/Width'
      length:
        $ref: '#/definitions/Length'
      volume:
        $ref: '#/definitions/Volume'
      amount:
        description: ''
        example: 50000
        type: string
      requirements:
        $ref: '#/definitions/Requirements'
    required:
    - name
    - description
    - type_of_load
    - weight
    - height
    - width
    - length
    - volume
    - amount
    - requirements
  Weight:
    title: Weight
    example:
      value: 33
      unit_code: t
    type: object
    properties:
      value:
        description: ''
        example: 33
        type: integer
        format: int32
      unit_code:
        description: ''
        example: t
        type: string
    required:
    - value
    - unit_code
  Height:
    title: Height
    example:
      value: 26
      unit_code: m
    type: object
    properties:
      value:
        description: ''
        example: 26
        type: integer
        format: int32
      unit_code:
        description: ''
        example: m
        type: string
    required:
    - value
    - unit_code
  Width:
    title: Width
    example:
      value: 16
      unit_code: m
    type: object
    properties:
      value:
        description: ''
        example: 16
        type: integer
        format: int32
      unit_code:
        description: ''
        example: m
        type: string
    required:
    - value
    - unit_code
  Length:
    title: Length
    example:
      value: 16
      unit_code: m
    type: object
    properties:
      value:
        description: ''
        example: 16
        type: integer
        format: int32
      unit_code:
        description: ''
        example: m
        type: string
    required:
    - value
    - unit_code
  Volume:
    title: Volume
    example:
      value: 16
      unit_code: m3
    type: object
    properties:
      value:
        description: ''
        example: 16
        type: integer
        format: int32
      unit_code:
        description: ''
        example: m3
        type: string
    required:
    - value
    - unit_code
  Requirements:
    title: Requirements
    example:
      required_adr_classes:
      - 1
      required_ways_of_loading:
      - side
      required_truck_bodies:
      - 20
      - 16
      is_truck_crane_required: true
      is_lift_required: false
      is_for_clearance: true
      is_tir_cable_required: true
      is_ftl: true
      is_tracking_system_required: true
      shipping_remarks: brak dodatkowych wymagaD
    type: object
    properties:
      required_adr_classes:
        description: ''
        example:
        - 1
        type: array
        items:
          type: string
      required_ways_of_loading:
        description: ''
        example:
        - side
        type: array
        items:
          type: string
      required_truck_bodies:
        description: ''
        example:
        - 20
        - 16
        type: array
        items:
          type: string
      is_truck_crane_required:
        description: ''
        example: true
        type: boolean
      is_lift_required:
        description: ''
        example: false
        type: boolean
      is_for_clearance:
        description: ''
        example: true
        type: boolean
      is_tir_cable_required:
        description: ''
        example: true
        type: boolean
      is_ftl:
        description: ''
        example: true
        type: boolean
      is_tracking_system_required:
        description: ''
        example: true
        type: boolean
      shipping_remarks:
        description: ''
        example: brak dodatkowych wymagaD
        type: string
    required:
    - required_adr_classes
    - required_ways_of_loading
    - required_truck_bodies
    - is_truck_crane_required
    - is_lift_required
    - is_for_clearance
    - is_tir_cable_required
    - is_ftl
    - is_tracking_system_required
    - shipping_remarks
  EditShipmentreqests(multi)request:
    title: Edit ShipmentReqests (multi)Request
    example:
      name: 13.07.2017 2005
      number: 123456789
      status: in_progress
      ready_to_send: 2018-04-11T09:47:42.0000000+00:00
      freights: []
      spots:
      - name: Hurtownia
        type: loading
        timespans:
          begin: 2018-04-15T09:47:42.0000000+00:00
          end: 2018-04-15T09:47:42.0000000+00:00
        place:
          address:
            locality: Munchen
            postal_code: 80331
            country: DE
            street: Ulica
            number: 2
          coordinates:
            latitude: -90
            longitude: -180
      - name: Lidl
        type: unloading
        timespans:
          begin: 2018-04-15T09:47:42.0000000+00:00
          end: 2018-04-15T09:47:42.0000000+00:00
        place:
          address:
            locality: WrocBaw
            postal_code: 50-064
            country: PL
            street: Zwidnicka
            number: 1
          coordinates:
            latitude: -90
            longitude: -180
      loads:
      - name: Chemicals
        description: Test
        type_of_load: box
        weight:
          value: 50
          unit_code: kg
        height:
          value: 26
          unit_code: kg
        width:
          value: 16
          unit_code: kg
        length:
          value: 16
          unit_code: kg
        volume:
          value: 16
          unit_code: kg
        amount: 50000
        requirements:
          required_adr_classes:
          - 1
          required_ways_of_loading:
          - side
          required_truck_bodies:
          - 20
          is_truck_crane_required: true
          is_lift_required: false
          is_for_clearance: true
          is_tir_cable_required: true
          is_ftl: true
          is_tracking_system_required: true
          shipping_remarks: brak dodatkowych wymagaD
    type: object
    properties:
      name:
        description: ''
        example: 13.07.2017 2005
        type: string
      number:
        description: ''
        example: 123456789
        type: string
      status:
        description: ''
        example: in_progress
        type: string
      ready_to_send:
        description: ''
        example: 4/11/2018 9:47:42 AM
        type: string
      freights:
        description: ''
        example: []
        type: array
        items:
          type: string
      spots:
        description: ''
        example:
        - name: Hurtownia
          type: loading
          timespans:
            begin: 2018-04-15T09:47:42.0000000+00:00
            end: 2018-04-15T09:47:42.0000000+00:00
          place:
            address:
              locality: Munchen
              postal_code: 80331
              country: DE
              street: Ulica
              number: 2
            coordinates:
              latitude: -90
              longitude: -180
        - name: Lidl
          type: unloading
          timespans:
            begin: 2018-04-15T09:47:42.0000000+00:00
            end: 2018-04-15T09:47:42.0000000+00:00
          place:
            address:
              locality: WrocBaw
              postal_code: 50-064
              country: PL
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        type: array
        items:
          $ref: '#/definitions/Spot'
      loads:
        description: ''
        example:
        - name: Chemicals
          description: Test
          type_of_load: box
          weight:
            value: 50
            unit_code: kg
          height:
            value: 26
            unit_code: kg
          width:
            value: 16
            unit_code: kg
          length:
            value: 16
            unit_code: kg
          volume:
            value: 16
            unit_code: kg
          amount: 50000
          requirements:
            required_adr_classes:
            - 1
            required_ways_of_loading:
            - side
            required_truck_bodies:
            - 20
            is_truck_crane_required: true
            is_lift_required: false
            is_for_clearance: true
            is_tir_cable_required: true
            is_ftl: true
            is_tracking_system_required: true
            shipping_remarks: brak dodatkowych wymagaD
        type: array
        items:
          $ref: '#/definitions/Load20'
    required:
    - name
    - number
    - status
    - ready_to_send
    - freights
    - spots
    - loads
  Load20:
    title: Load20
    example:
      name: Chemicals
      description: Test
      type_of_load: box
      weight:
        value: 50
        unit_code: kg
      height:
        value: 26
        unit_code: kg
      width:
        value: 16
        unit_code: kg
      length:
        value: 16
        unit_code: kg
      volume:
        value: 16
        unit_code: kg
      amount: 50000
      requirements:
        required_adr_classes:
        - 1
        required_ways_of_loading:
        - side
        required_truck_bodies:
        - 20
        is_truck_crane_required: true
        is_lift_required: false
        is_for_clearance: true
        is_tir_cable_required: true
        is_ftl: true
        is_tracking_system_required: true
        shipping_remarks: brak dodatkowych wymagaD
    type: object
    properties:
      name:
        description: ''
        example: Chemicals
        type: string
      description:
        description: ''
        example: Test
        type: string
      type_of_load:
        description: ''
        example: box
        type: string
      weight:
        $ref: '#/definitions/Weight'
      height:
        $ref: '#/definitions/Height'
      width:
        $ref: '#/definitions/Width'
      length:
        $ref: '#/definitions/Length'
      volume:
        $ref: '#/definitions/Volume'
      amount:
        description: ''
        example: 50000
        type: integer
        format: int32
      requirements:
        $ref: '#/definitions/Requirements'
    required:
    - name
    - description
    - type_of_load
    - weight
    - height
    - width
    - length
    - volume
    - amount
    - requirements
  EditSrCollectionrequest:
    title: Edit SR CollectionRequest
    example:
      ids:
      - 1
      - 2
      data:
        ready_to_send:
          begin: 2017-08-30T09:55:42.0000000+00:00
          end: 2017-08-30T09:55:42.0000000+00:00
        spots:
        - name: Lidl
          type: unloading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Monachium
              postal_code: 53-342
              country: DE
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        - name: Lidl
          type: loading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Monachium
              postal_code: 53-342
              country: DE
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
    type: object
    properties:
      ids:
        description: ''
        example:
        - 1
        - 2
        type: array
        items:
          type: integer
          format: int32
      data:
        $ref: '#/definitions/Data'
    required:
    - ids
    - data
  Data:
    title: Data
    example:
      ready_to_send:
        begin: 2017-08-30T09:55:42.0000000+00:00
        end: 2017-08-30T09:55:42.0000000+00:00
      spots:
      - name: Lidl
        type: unloading
        timespans:
          begin: 2018-07-20T09:47:42.0000000+00:00
          end: 2018-07-20T09:47:42.0000000+00:00
        place:
          address:
            locality: Monachium
            postal_code: 53-342
            country: DE
            street: Zwidnicka
            number: 1
          coordinates:
            latitude: -90
            longitude: -180
      - name: Lidl
        type: loading
        timespans:
          begin: 2018-07-20T09:47:42.0000000+00:00
          end: 2018-07-20T09:47:42.0000000+00:00
        place:
          address:
            locality: Monachium
            postal_code: 53-342
            country: DE
            street: Zwidnicka
            number: 1
          coordinates:
            latitude: -90
            longitude: -180
    type: object
    properties:
      ready_to_send:
        $ref: '#/definitions/ReadyToSend'
      spots:
        description: ''
        example:
        - name: Lidl
          type: unloading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Monachium
              postal_code: 53-342
              country: DE
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        - name: Lidl
          type: loading
          timespans:
            begin: 2018-07-20T09:47:42.0000000+00:00
            end: 2018-07-20T09:47:42.0000000+00:00
          place:
            address:
              locality: Monachium
              postal_code: 53-342
              country: DE
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        type: array
        items:
          $ref: '#/definitions/Spot'
    required:
    - ready_to_send
    - spots
  EditSrCollection(local)request:
    title: Edit SR Collection(local)Request
    example:
      ids:
      - 1
      - 2
      data:
        spots:
        - name: Logintrans Sp. z o. o.2
          type: loading
          place:
            address:
              locality: WrocBaw
              postal_code: 52-200
              country: PL
              street: Chabrowa
              number: 4
            coordinates:
              latitude: -90
              longitude: -180
    type: object
    properties:
      ids:
        description: ''
        example:
        - 1
        - 2
        type: array
        items:
          type: integer
          format: int32
      data:
        $ref: '#/definitions/Data36'
    required:
    - ids
    - data
  Data36:
    title: Data36
    example:
      spots:
      - name: Logintrans Sp. z o. o.2
        type: loading
        place:
          address:
            locality: WrocBaw
            postal_code: 52-200
            country: PL
            street: Chabrowa
            number: 4
          coordinates:
            latitude: -90
            longitude: -180
    type: object
    properties:
      spots:
        description: ''
        example:
        - name: Logintrans Sp. z o. o.2
          type: loading
          place:
            address:
              locality: WrocBaw
              postal_code: 52-200
              country: PL
              street: Chabrowa
              number: 4
            coordinates:
              latitude: -90
              longitude: -180
        type: array
        items:
          $ref: '#/definitions/Spot37'
    required:
    - spots
  Spot37:
    title: Spot37
    example:
      name: Logintrans Sp. z o. o.2
      type: loading
      place:
        address:
          locality: WrocBaw
          postal_code: 52-200
          country: PL
          street: Chabrowa
          number: 4
        coordinates:
          latitude: -90
          longitude: -180
    type: object
    properties:
      name:
        description: ''
        example: Logintrans Sp. z o. o.2
        type: string
      type:
        description: ''
        example: loading
        type: string
      place:
        $ref: '#/definitions/Place38'
    required:
    - name
    - type
    - place
  Place38:
    title: Place38
    example:
      address:
        locality: WrocBaw
        postal_code: 52-200
        country: PL
        street: Chabrowa
        number: 4
      coordinates:
        latitude: -90
        longitude: -180
    type: object
    properties:
      address:
        $ref: '#/definitions/Address'
      coordinates:
        $ref: '#/definitions/Coordinates40'
    required:
    - address
    - coordinates
  Coordinates40:
    title: Coordinates40
    example:
      latitude: -90
      longitude: -180
    type: object
    properties:
      latitude:
        description: ''
        example: -90
        type: integer
        format: int32
      longitude:
        description: ''
        example: -180
        type: integer
        format: int32
    required:
    - latitude
    - longitude
  PatchShipmentreqestsrequest:
    title: Patch ShipmentReqestsRequest
    example:
      name: 13.07.2017 2005
      number: 123456789
      status: in_progress
      ready_to_send:
        begin: 2017-10-18T22:00:00.0000000+00:00
        end: 2017-10-18T22:00:00.0000000+00:00
      freights: []
      spots:
      - name: Hurtownia
        type: loading
        timespans:
          begin: 2017-10-18T22:00:00.0000000+00:00
          end: 2017-10-18T22:00:00.0000000+00:00
        place:
          address:
            locality: Munchen
            postal_code: 80331
            country: DE
            street: Ulica
            number: 2
          coordinates:
            latitude: -90
            longitude: -180
      - name: Lidl
        type: unloading
        timespans:
          begin: 2017-10-18T22:00:00.0000000+00:00
          end: 2017-10-18T22:00:00.0000000+00:00
        place:
          address:
            locality: WrocBaw
            postal_code: 50-064
            country: PL
            street: Zwidnicka
            number: 1
          coordinates:
            latitude: -90
            longitude: -180
      loads:
      - name: Chemicals
        description: Test
        type_of_load: box
        weight:
          value: 50
          unit_code: kg
        height:
          value: 26
          unit_code: kg
        width:
          value: 16
          unit_code: kg
        length:
          value: 16
          unit_code: kg
        volume:
          value: 16
          unit_code: kg
        amount: 50000
        requirements:
          required_adr_classes:
          - 1
          required_ways_of_loading:
          - side
          required_truck_bodies:
          - 20
          is_truck_crane_required: true
          is_lift_required: false
          is_for_clearance: true
          is_tir_cable_required: true
          is_ftl: true
          is_tracking_system_required: true
          shipping_remarks: brak dodatkowych wymagaD
    type: object
    properties:
      name:
        description: ''
        example: 13.07.2017 2005
        type: string
      number:
        description: ''
        example: 123456789
        type: string
      status:
        description: ''
        example: in_progress
        type: string
      ready_to_send:
        $ref: '#/definitions/ReadyToSend'
      freights:
        description: ''
        example: []
        type: array
        items:
          type: string
      spots:
        description: ''
        example:
        - name: Hurtownia
          type: loading
          timespans:
            begin: 2017-10-18T22:00:00.0000000+00:00
            end: 2017-10-18T22:00:00.0000000+00:00
          place:
            address:
              locality: Munchen
              postal_code: 80331
              country: DE
              street: Ulica
              number: 2
            coordinates:
              latitude: -90
              longitude: -180
        - name: Lidl
          type: unloading
          timespans:
            begin: 2017-10-18T22:00:00.0000000+00:00
            end: 2017-10-18T22:00:00.0000000+00:00
          place:
            address:
              locality: WrocBaw
              postal_code: 50-064
              country: PL
              street: Zwidnicka
              number: 1
            coordinates:
              latitude: -90
              longitude: -180
        type: array
        items:
          $ref: '#/definitions/Spot'
      loads:
        description: ''
        example:
        - name: Chemicals
          description: Test
          type_of_load: box
          weight:
            value: 50
            unit_code: kg
          height:
            value: 26
            unit_code: kg
          width:
            value: 16
            unit_code: kg
          length:
            value: 16
            unit_code: kg
          volume:
            value: 16
            unit_code: kg
          amount: 50000
          requirements:
            required_adr_classes:
            - 1
            required_ways_of_loading:
            - side
            required_truck_bodies:
            - 20
            is_truck_crane_required: true
            is_lift_required: false
            is_for_clearance: true
            is_tir_cable_required: true
            is_ftl: true
            is_tracking_system_required: true
            shipping_remarks: brak dodatkowych wymagaD
        type: array
        items:
          $ref: '#/definitions/Load20'
    required:
    - name
    - number
    - status
    - ready_to_send
    - freights
    - spots
    - loads
